chore(docs): Review previous steps on roadmap
Malaguth/skill-tracking pull request #28
Opened 2024-01-12 00:38 UTC by danielfmf25

- Detail the completed and pending steps

2024-01-12 01:01 UTC, Malaguth requested changes
Rename the `chore` commits to use `docs`  instead directly.

2024-01-12 01:03 UTC, Malaguth requested changes
Amend the commit that removes the unwanted doc folder or rename it using the git commit convention available [here](https://www.conventionalcommits.org/en/v1.0.0/).

2024-01-12 01:24 UTC, Malaguth requested changes

2024-01-12 01:24 UTC, Malaguth commented on doc/review_steps_roadmap.md
> +# CONCLUSION
This comment makes sense in case of migrating the content to the other pages using some title like `# Team review`

2024-01-12 01:24 UTC, Malaguth commented on doc/review_steps_roadmap.md
> +# Review previous steps on roadmap
I understand that you created a new file, but in some cases, it is better to update the old ones with the content of what we learned. Doing it prevents outdated files with wrong content and centralizes all the content regarding a topic inside the same file.

2024-01-12 01:26 UTC, Malaguth commented
Maybe would be good to add the new [Git Flow Roadmap](https://roadmap.sh/r?id=65a081852ae39e5b7bc54f8c) to the documentation

2024-01-15 19:11 UTC, danielfmf25 commented
The requested changes have been made. The doubt remains regarding the topics not yet covered, in my point of view. I suggest leaving a separate document so that, when addressed, such topics can be incorporated into other existing documents.

2024-01-16 23:51 UTC, Malaguth approved these changes

2024-01-16 23:51 UTC, merged